version: "3"
services:
  server:
    image: mysql:5.5
    volumes:
      - "//c/docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=server
    depends_on:
      - server
